# Generated by Django 3.2.19 on 2023-05-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230520_0601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='in_gre',
            new_name='ingredients',
        ),
    ]
